apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-achmea
  namespace: zorginzicht-acc
spec:
  rules:
    - host: zorgpolis.acc.docker.achmea.local
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: ui
                port:
                  number: 5000
